# Generated by Django 2.1.3 on 2020-03-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20200310_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_deliver_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.FloatField(default=0),
        ),
    ]
