# Generated by Django 2.1.3 on 2020-03-25 13:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0010_auto_20200325_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('F', 'Finished'), ('P', 'Paid'), ('O', 'Ordered')], max_length=1)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('P', 'Paid'), ('O', 'Ordered'), ('S', 'Shipping'), ('A', 'Arrived'), ('W', 'Waiting')], max_length=1)),
                ('order', models.ForeignKey(null=True, on_delete='CASCADE', to='purchase.Order')),
                ('product', models.ForeignKey(null=True, on_delete='SET_NULL', to='product.Product')),
            ],
        ),
    ]
