# Generated by Django 2.1.3 on 2020-02-17 18:37

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0007_auto_20200218_0137'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sellerID',
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=djongo.models.fields.ArrayReferenceField(blank=True, default=0, on_delete=djongo.models.fields.ArrayReferenceField._on_delete, to='profile.Profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='proDuctDesc',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
