# Generated by Django 2.1.3 on 2020-02-17 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200218_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productID',
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='profile.Profile'),
        ),
    ]
