# Generated by Django 2.1.3 on 2020-03-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productType',
            field=models.CharField(choices=[('R', 'Reserve'), ('L', 'Launch'), ('A', 'Add')], default='A', max_length=1),
        ),
    ]
