# Generated by Django 2.1.3 on 2020-03-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200309_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productType',
            field=models.CharField(choices=[('A', 'Add'), ('R', 'Reserve'), ('L', 'Launch')], default='A', max_length=1),
        ),
    ]
