# Generated by Django 2.1.3 on 2020-03-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20200309_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productType',
            field=models.CharField(choices=[('L', 'Launch'), ('R', 'Reserve'), ('N', 'Not available'), ('A', 'Add')], default='A', max_length=1),
        ),
    ]
