# Generated by Django 2.1.3 on 2020-03-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20200310_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productType',
            field=models.CharField(choices=[('R', 'Reserve'), ('A', 'Add'), ('L', 'Launch'), ('N', 'Not available')], default='A', max_length=1),
        ),
    ]
