# Generated by Django 2.1.3 on 2020-03-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20200310_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productType',
            field=models.CharField(choices=[('A', 'Add'), ('R', 'Reserve'), ('N', 'Not available'), ('L', 'Launch')], default='A', max_length=1),
        ),
    ]
