# Generated by Django 2.1.3 on 2020-02-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('S', 'Seller'), ('M', 'Moderator'), ('C', 'Customer')], max_length=1),
        ),
    ]
