# Generated by Django 2.1.3 on 2020-02-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_auto_20200215_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('C', 'Customer'), ('S', 'Seller'), ('M', 'Moderator')], max_length=1),
        ),
    ]
