# Generated by Django 2.1.3 on 2020-02-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_auto_20200215_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nat_id',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
