# Generated by Django 2.1.3 on 2020-02-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_profile_nat_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='storeName',
            new_name='store_name',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('S', 'Seller'), ('M', 'Moderator'), ('C', 'Customer')], max_length=1),
        ),
    ]
