# Generated by Django 2.1.3 on 2020-02-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('profile', '0005_auto_20200217_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='products',
        ),
        migrations.AddField(
            model_name='profile',
            name='products',
            field=models.ManyToManyField(to='product.Product'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('M', 'Moderator'), ('C', 'Customer'), ('S', 'Seller')], max_length=1),
        ),
    ]
