# Generated by Django 2.1.3 on 2020-02-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0006_auto_20200217_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='products',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('C', 'Customer'), ('S', 'Seller'), ('M', 'Moderator')], max_length=1),
        ),
    ]
