# Generated by Django 2.1.3 on 2020-02-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0008_auto_20200218_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('C', 'Customer'), ('S', 'Seller'), ('M', 'Moderator')], max_length=1),
        ),
    ]
