# Generated by Django 2.1.3 on 2020-02-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0009_auto_20200218_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('S', 'Seller'), ('M', 'Moderator'), ('C', 'Customer')], max_length=1),
        ),
    ]
