# Generated by Django 2.1.3 on 2020-02-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0010_auto_20200218_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('M', 'Moderator'), ('S', 'Seller'), ('C', 'Customer')], max_length=1),
        ),
    ]
