# Generated by Django 2.1.3 on 2020-03-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0011_auto_20200218_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('S', 'Seller'), ('M', 'Moderator'), ('C', 'Customer')], max_length=1),
        ),
    ]
