# Generated by Django 2.1.3 on 2020-03-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0012_auto_20200309_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('S', 'Seller'), ('C', 'Customer'), ('M', 'Moderator')], max_length=1),
        ),
    ]
