# Generated by Django 2.1.3 on 2020-03-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0013_auto_20200309_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to='product.Product'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('M', 'Moderator'), ('S', 'Seller'), ('C', 'Customer')], max_length=1),
        ),
    ]
