# Generated by Django 2.1.3 on 2020-03-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0016_auto_20200310_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('M', 'Moderator'), ('S', 'Seller'), ('C', 'Customer')], max_length=1),
        ),
    ]
